### ISSUE TITLE
Large file upload error - read ECONNRESET

### ISSUE THREAD

**Issue by Fire-Brand** [FallenTech/streaming-s3#16]
I'm trying to upload a large CSV file (500Mb~700Mb).
I've used Example 3 from the readme file (**Uploading remote file without callback and options**), but i just used `post` instead of `get` (have to use post)
and i ran into this error:

```
Upload error:  { Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at TLSWrap.onread (net.js:619:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```
Any idea what's going on?

**Comment by talha-asad** [comment]
That could mean a connection being reset to either the remote file or the S3 server. I would recommend trying to download that file locally and trying to upload it, if it works, the remote server is likely the culprit and is timing out.

**Comment by Fire-Brand** [comment]
@talha-asad tried uploading it from local file and got the same error.
(When i tired a small file everything went ok)

**Comment by Fire-Brand** [comment]
Found this:
```
Individual Amazon S3 objects can range in size from a minimum of 0 bytes to a maximum of 5 terabytes. The largest object that can be uploaded in a single PUT is 5 gigabytes. For objects larger than 100 megabytes, customers should consider using the Multipart Upload capability.
```
taken from: https://aws.amazon.com/s3/faqs/

**Comment by talha-asad** [comment]
How small was the file that went smoothly

The package does use multipart uploading, and your case doesn't seems to break any of those rules. I will give it a try later today by uploading a large CSV of 800 MB.

**Comment by Fire-Brand** [comment]
When i added the options explicitly like so:
```javascript
{
    concurrentParts: 5,
    waitTime: 60000,
    retries: 5,
    sdkRetries: 6,
    maxPartSize: 10 * 1024 * 1024
}
```
I managed to upload a 104Mb file successfully, but a bigger, remote file still gave the same error, will now try to play with configurations a little bit, and let you know what happened.

**Comment by Fire-Brand** [comment]
So, trying to upload a ~740Mb file gave me about 50% errors on parts:
```
Upload error:  { RequestTimeTooSkewed: The difference between the request time and the current time is too large.
    at Request.extractError (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (path/to/project/node_modules/streaming-s3/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The difference between the request time and the current time is too large.',
  code: 'RequestTimeTooSkewed',
  region: null,
  time: 2018-01-04T12:00:35.647Z,
  requestId: 'DF3C33E9FF287B4B',
  extendedRequestId: '1/vUT63Vdh4FuF2vbYDUdX4J4CVcPxZPYy3pjGiU6mVbExrkt73ObnQ6krH/b+HcG3kKUXQjM4Q=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 53.565890708982835 }
```

**Comment by Fire-Brand** [comment]
I managed to upload a local file with:
```javascript
{
	concurrentParts: 10,
	waitTime: 0,
	retries: 5,
	sdkRetries: 6,
	maxPartSize: 20 * 1024 * 1024
}
```

But remote still failed, so i added a `Connection: Keep-Alive` header and tried to upload a remote file again - still had the same issue...
I had theory that it might have something to do with my local environment (mac) so i tired to do it on my dev server (Ubuntu), and everything went smoothly so far (files at around 120 Mb).

If larger files will cause issues again i'll notify here, for the mean time, this can be closed.

Thanks @talha-asad !
